theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
cursorline = true
cursorcolumn = true
bufferline = "multiple"
true-color = true
color-modes = true
completion-replace = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "|"
mode.normal = "😄"
mode.insert = "🤔"
mode.select = "😠"

[editor.lsp]
display-messages = true
display-progress-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":write"
Cmd-s = ":write"
A-q = ":write-buffer-close"
